services:
  nginx:
    image: nginx:alpine
    container_name: videoeditor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount certs read-only
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: videoeditor-frontend
    env_file:
      - .env
    environment:
      # Ensure server-side code can construct proper callback URLs
      AUTH_BASE_URL: https://trykimu.com
      AUTH_TRUSTED_ORIGINS: https://trykimu.com,https://www.trykimu.com
      AUTH_COOKIE_DOMAIN: trykimu.com
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 5173
    # ports:
    #   - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: videoeditor-backend
    env_file:
      - .env
    environment:
      AUTH_BASE_URL: https://trykimu.com
      AUTH_TRUSTED_ORIGINS: https://trykimu.com,https://www.trykimu.com
      AUTH_COOKIE_DOMAIN: trykimu.com
      NODE_ENV: production
      PORT: 8000
    # ports:
    #   - "8000:8000"
    volumes:
      - ./out:/app/out
    # Memory configuration for video rendering
    mem_limit: 2g
    memswap_limit: 2g
    shm_size: 1g

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videoeditor-fastapi
