version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: videoeditor-frontend
    env_file:
      - .env
    environment:
      # Development-specific overrides
      PROD_DOMAIN: localhost
      AUTH_BASE_URL: http://localhost:5173
      AUTH_TRUSTED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      AUTH_COOKIE_DOMAIN: localhost
      NODE_ENV: development
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: videoeditor-backend
    env_file:
      - .env
    environment:
      # Development-specific overrides
      PROD_DOMAIN: localhost
      AUTH_BASE_URL: http://localhost:5173
      AUTH_TRUSTED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
      AUTH_COOKIE_DOMAIN: localhost
      NODE_ENV: development
    ports:
      - "8000:8000"

  fastapi:
    ports:
      - "3000:3000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videoeditor-fastapi
